### ISSUE TITLE
it crashed when comment is empty.

### ISSUE THREAD

**Issue by youleiy** [JoMingyu/google-play-scraper#18]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/code/app-ads/.venv/lib/python3.7/site-packages/google_play_scraper/__init__.py", line 54, in app
    content = spec.extract_content(res)
  File "/root/code/app-ads/.venv/lib/python3.7/site-packages/google_play_scraper/constants/element.py", line 26, in extract_content
    result = self.post_processor(result)
  File "/root/code/app-ads/.venv/lib/python3.7/site-packages/google_play_scraper/constants/element.py", line 85, in <lambda>
    "comments": ElementSpec(15, [0], lambda container: [item[4] for item in container]),
TypeError: 'NoneType' object is not iterable

**Comment by JoMingyu** [comment]
My response was too late, but a new patch will be released this week. sorry ;(

**Comment by JoMingyu** [comment]
it fixed in the [0.0.1.2 release](https://pypi.org/manage/project/google-play-scraper/release/0.0.1.2/).
