### ISSUE TITLE
Multiple calls to reviews function crashes

### ISSUE THREAD

**Issue by alfa-jess** [JoMingyu/google-play-scraper#37]
Hi !
Thanks for such a nice and useful repository, I am currently facing an error. I am trying to scrape all reviews from an app by doing several calls to the function reviews. After several calls of 

`result = reviews(
            'com.nianticlabs.pokemongo',
            lang='en',  # defaults to 'en'
            country='us', # defaults to 'us'
            sort=Sort.MOST_RELEVANT,  # defaults to Sort.MOST_RELEVANT
            count=100,  # defaults to 100
        )`

I get the following error:
```
Traceback (most recent call last):
  File "/Users/Documents/Documents//google_play_scraper/google_play_scraper/features/reviews.py", line 124, in <module>
    pagination_token=pagination_token
  File "/Users/Documents/Documents/google_play_scraper/google_play_scraper/features/reviews.py", line 73, in reviews
    url, app_id, sort, _count, filter_score_with, pagination_token
  File "/Users/Documents/google_play_scraper/google_play_scraper/features/reviews.py", line 34, in _fetch_review_items
    {"content-type": "application/x-www-form-urlencoded"},
  File "/Applications/anaconda3/envs/sentiment_analysis/lib/python3.7/site-packages/google_play_scraper/utils/request.py", line 33, in post
    return _urlopen(Request(url, data=data, headers=headers))
  File "/Applications/anaconda3/envs/sentiment_analysis/lib/python3.7/site-packages/google_play_scraper/utils/request.py", line 27, in _urlopen
    return resp.read().decode("UTF-8")
  File "/Applications/anaconda3/envs/sentiment_analysis/lib/python3.7/http/client.py", line 467, in read
    s = self.fp.read()
  File "/Applications/anaconda3/envs/sentiment_analysis/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/Applications/anaconda3/envs/sentiment_analysis/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/Applications/anaconda3/envs/sentiment_analysis/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:2555)

Process finished with exit code 1
```

Do you have by any chance an idea of how to fix this bug?

Thank you in advance :)

**Comment by JoMingyu** [comment]
Thanks! I'll fix it ASAP.

**Comment by JoMingyu** [comment]
It works on my machine(Python 3.6 ~ 3.8 with MacOS Mojave and Windows 10) :(

Please create a new clean Python virtual environment, install library and retry. If that doesn't work, please comment your operating system info and the results of running the commands below.

- `python -c "import ssl; print(ssl.OPENSSL_VERSION)"`
- `pip list` (in virtualenv)

**Comment by alfa-jess** [comment]
It worked ! I followed your suggestion of creating a new environment and I decided to try with Python 3.6
Thanks a lot :)
I was using MacOs Catalina and  Python 3.7

**Comment by JoMingyu** [comment]
> It worked ! I followed your suggestion of creating a new environment and I decided to try with Python 3.6
> Thanks a lot :)
> I was using MacOs Catalina and Python 3.7

good news !

**Comment by jacobtomlinson** [comment]
This is likely caused by `openssl==1.1.1e`. Downgrading this package to `1.1.1d` probably resolved the issue.
